package com.causa.infrastructure.persistence.entity;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Context Data JPA Entity — maps to the {@code context_data} table.
 *
 * <p>Stores raw observability content (Kubernetes logs, JFR reports, Kruize metrics)
 * collected by MCP servers during the diagnostic pipeline, along with optional
 * vector embeddings for RAG-based similarity search.
 *
 * <p>ID convention: {@code ctxd_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "context_data")
public class ContextDataEntity extends BaseEntity {

    /** Application-generated PK: {@code ctxd_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /**
     * FK to {@code alerts.id}. Loaded lazily to avoid N+1 on bulk reads.
     * Use {@link #getAlertId()} to access the ID without triggering a join.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alert_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_context_data_alert"))
    private AlertEntity alert;

    /** Container name — denormalised for fast indexed lookups. */
    @Column(nullable = false, length = 255)
    private String containerName;

    /**
     * Type of context collected.
     * Values: {@code K8S_LOGS}, {@code JFR_REPORT}, {@code KRUIZE_METRICS}.
     */
    @Column(nullable = false, length = 64)
    private String contextType;

    /** Raw text content of the context chunk. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * Extra metadata about this context chunk stored as JSONB.
     * Shape: free-form; e.g. {@code { "source": "kubernetes", "lines": 200 }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode contextMetadata;

    // -------------------------------------------------------------------------
    // Convenience accessor
    // -------------------------------------------------------------------------

    /** Returns the alert's PK without forcing a lazy load of the full entity. */
    public String getAlertId() {
        return alert != null ? alert.getId() : null;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public AlertEntity getAlert() { return alert; }
    public void setAlert(AlertEntity alert) { this.alert = alert; }

    public String getContainerName() { return containerName; }
    public void setContainerName(String containerName) { this.containerName = containerName; }

    public String getContextType() { return contextType; }
    public void setContextType(String contextType) { this.contextType = contextType; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public JsonNode getContextMetadata() { return contextMetadata; }
    public void setContextMetadata(JsonNode contextMetadata) { this.contextMetadata = contextMetadata; }
}
