package com.causa.infrastructure.persistence.entity;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Diagnostic JPA Entity — maps to the {@code diagnostics} table.
 *
 * <p>Stores LLM-generated root cause analysis output along with token analytics,
 * evidence, recommendations, and validation data.
 * Column names are derived automatically from field names via
 * {@code CamelCaseToUnderscoresNamingStrategy}.
 *
 * <p>ID convention: {@code diag_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "diagnostics")
public class DiagnosticEntity extends BaseEntity {

    /** Application-generated PK: {@code diag_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /**
     * FK to {@code alerts.id}. Loaded lazily to avoid N+1 on bulk reads.
     * Use {@link #getAlertId()} to access the ID without triggering a join.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alert_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_diagnostics_alert"))
    private AlertEntity alert;

    /**
     * Lifecycle status of this diagnostic.
     * Values: {@code PENDING}, {@code PROCESSING}, {@code COMPLETED}, {@code FAILED}.
     */
    @Column(nullable = false, length = 32)
    private String status;

    /** Short human-readable title for the identified issue. */
    @Column(length = 255)
    private String issueTitle;

    /** Plain-language description of the issue. */
    @Column(columnDefinition = "TEXT")
    private String issueDescription;

    /** Classification of the issue (e.g. {@code OOM_KILLED}, {@code HIGH_MEMORY_PRESSURE}). */
    @Column(length = 64)
    private String issueType;

    /** One-paragraph root cause summary produced by the LLM. */
    @Column(columnDefinition = "TEXT")
    private String rootCauseSummary;

    /**
     * RCA confidence metadata stored as JSONB.
     * Shape: {@code { "rca_score": 0.92, "solution_score": 0.85, "summary": "..." }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode confidenceInfo;

    /**
     * LLM provider and token analytics stored as JSONB.
     * Shape: {@code { "provider": "anthropic", "model": "...", "input_tokens": 1024, "output_tokens": 512, "latency_ms": 3200 }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode llmInfo;

    /**
     * Ordered array of actionable remediation steps stored as JSONB.
     * Each element: {@code { "solution": "...", "justification": "...", "success_probability": "High", "implementation_notes": "..." }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode recommendations;

    /**
     * Supporting evidence bundle stored as JSONB.
     * Shape: {@code { "supporting_logs": [...], "evidences": [...], "confidence_summary": { "rca_confidence_score": 0.0, "summary_text": "..." } }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode evidence;

    /** Outcome of the optional validation step (e.g. {@code VALIDATED}, {@code DISPUTED}). */
    @Column(length = 64)
    private String validationResult;

    /**
     * Detailed validation output stored as JSONB.
     * Shape: {@code { "assertions": [...], "mismatches": [...] }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode validationData;

    /**
     * Extensible metadata bag stored as JSONB.
     * Shape: {@code { "llm_notes": "...", <future fields> }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode diagnosticsMetadata;

    /** Free-text remarks added by the system or an operator. */
    @Column(columnDefinition = "TEXT")
    private String remarks;

    /** Identifies what triggered this diagnostic (default: {@code AUTOMATIC}). */
    @Column(length = 255)
    private String createdBy = "AUTOMATIC";

    // -------------------------------------------------------------------------
    // Convenience accessor — avoids loading the full AlertEntity proxy
    // -------------------------------------------------------------------------

    /** Returns the alert's PK without forcing a lazy load of the full entity. */
    public String getAlertId() {
        return alert != null ? alert.getId() : null;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public AlertEntity getAlert() { return alert; }
    public void setAlert(AlertEntity alert) { this.alert = alert; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getIssueTitle() { return issueTitle; }
    public void setIssueTitle(String issueTitle) { this.issueTitle = issueTitle; }

    public String getIssueDescription() { return issueDescription; }
    public void setIssueDescription(String issueDescription) { this.issueDescription = issueDescription; }

    public String getIssueType() { return issueType; }
    public void setIssueType(String issueType) { this.issueType = issueType; }

    public String getRootCauseSummary() { return rootCauseSummary; }
    public void setRootCauseSummary(String rootCauseSummary) { this.rootCauseSummary = rootCauseSummary; }

    public JsonNode getConfidenceInfo() { return confidenceInfo; }
    public void setConfidenceInfo(JsonNode confidenceInfo) { this.confidenceInfo = confidenceInfo; }

    public JsonNode getLlmInfo() { return llmInfo; }
    public void setLlmInfo(JsonNode llmInfo) { this.llmInfo = llmInfo; }

    public JsonNode getRecommendations() { return recommendations; }
    public void setRecommendations(JsonNode recommendations) { this.recommendations = recommendations; }

    public JsonNode getEvidence() { return evidence; }
    public void setEvidence(JsonNode evidence) { this.evidence = evidence; }

    public String getValidationResult() { return validationResult; }
    public void setValidationResult(String validationResult) { this.validationResult = validationResult; }

    public JsonNode getValidationData() { return validationData; }
    public void setValidationData(JsonNode validationData) { this.validationData = validationData; }

    public JsonNode getDiagnosticsMetadata() { return diagnosticsMetadata; }
    public void setDiagnosticsMetadata(JsonNode diagnosticsMetadata) { this.diagnosticsMetadata = diagnosticsMetadata; }

    public String getRemarks() { return remarks; }
    public void setRemarks(String remarks) { this.remarks = remarks; }

    public String getCreatedBy() { return createdBy; }
    public void setCreatedBy(String createdBy) { this.createdBy = createdBy; }
}
